separator_block_width=16

[nem_price]
command=curl -s 'https://api.coinmarketcap.com/v1/ticker/nem/?convert=EUR' | jq -r '.[].price_eur' | LC_ALL=C xargs /usr/bin/printf "%.3f€\n"
interval=300

[temperature]
command=~/.i3/temperature
interval=2

[battery]
command=~/.i3/battery
interval=60

[volume]
command=~/.i3/volume
interval=2

[time]
command=date "+%A, %e. %B, %H:%M"
interval=5
