separator_block_width=16

[mediaplayer]
instance=spotify
command=~/.i3/mediaplayer
interval=5
signal=10

[temperature]
command=~/.i3/temperature
interval=2

[battery]
command=~/.i3/battery
interval=60

[volume]
command=~/.i3/volume
interval=2

[time]
command=date "+%A, %e. %B, %H:%M"
interval=5
